services:
  # app:
  #   build: .
  #   container_name: bytebank
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - NODE_ENV=${NODE_ENV}
  #     - MONGODB_URI=${MONGODB_URI}
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongo

  mongo:
    image: mongo:7.0
    container_name: bytebank_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: